"""
json_utils.py

Production-ready utility for cleaning, fixing, and validating JSON outputs generated by LLMs.

Best Practices Included:
1. **Regex Extraction:** Intelligently extracts JSON blocks hidden inside conversational text.
2. **Syntax Repair:** Uses regex to strip trailing commas that often break standard json.loads().
3. **Resilience:** Attempts multiple parsing strategies before failing (Raw -> Extract -> Repair).
4. **Logging:** Detailed tracking of parsing failures and recovery steps to monitor model degradation.
"""

import json
import re
import logging
from typing import Dict, Any, Optional

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class LLMJSONParser:
    """
    A robust parser designed specifically to handle common formatting errors
    produced by Large Language Models when generating JSON.
    """
    
    @staticmethod
    def _extract_json_block(text: str) -> str:
        """
        Extracts the core JSON block from surrounding conversational text or markdown.
        Handles cases where the LLM says "Here is the JSON: ```json { ... } ``` Have a nice day!"
        """
        # 1. Strip markdown code block wrappers if they exist (```json ... ```)
        text = re.sub(r'^```(?:json)?\s*', '', text, flags=re.MULTILINE)
        text = re.sub(r'```\s*$', '', text, flags=re.MULTILINE)
        
        # 2. Extract the first valid JSON-like block (anything between the outermost { and })
        # DOTALL allows the dot to match newlines
        match = re.search(r'(\{.*\})', text, flags=re.DOTALL)
        if match:
            return match.group(1).strip()
            
        return text.strip()

    @staticmethod
    def _fix_trailing_commas(json_string: str) -> str:
        """
        Uses regex to remove trailing commas from objects and arrays.
        LLMs frequently generate `{"key": "value",}` which is invalid in strict JSON.
        """
        # Remove trailing commas before closing braces (objects)
        json_string = re.sub(r',\s*\}', '}', json_string)
        # Remove trailing commas before closing brackets (arrays)
        json_string = re.sub(r',\s*\]', ']', json_string)
        return json_string

    @staticmethod
    def parse(raw_output: str) -> Optional[Dict[str, Any]]:
        """
        Attempts to clean and parse the LLM output into a Python dictionary.
        
        Args:
            raw_output (str): The raw text output from the LLM.
            
        Returns:
            Dict: Parsed dictionary if successful, None otherwise.
        """
        if not raw_output:
            logger.error("Empty input provided to JSON parser.")
            return None
            
        logger.debug("Attempting to parse LLM JSON output...")
        
        # ---------------------------------------------------------------------
        # Attempt 1: Raw parse (Fastest path if the model generated perfect JSON)
        # ---------------------------------------------------------------------
        try:
            return json.loads(raw_output)
        except json.JSONDecodeError:
            pass # Move to cleanup
            
        # ---------------------------------------------------------------------
        # Attempt 2: Extract JSON block and strip markdown / conversational text
        # ---------------------------------------------------------------------
        cleaned_text = LLMJSONParser._extract_json_block(raw_output)
        try:
            return json.loads(cleaned_text)
        except json.JSONDecodeError:
            pass # Move to repair
            
        # ---------------------------------------------------------------------
        # Attempt 3: Fix common syntax errors (e.g., trailing commas)
        # ---------------------------------------------------------------------
        repaired_text = LLMJSONParser._fix_trailing_commas(cleaned_text)
        try:
            parsed_data = json.loads(repaired_text)
            logger.info("Successfully recovered JSON after regex syntax repair.")
            return parsed_data
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse LLM output even after repairs. Error: {e}")
            logger.error(f"Problematic Text Snippet: {repaired_text[:200]}...")
            return None


if __name__ == "__main__":
    # =========================================================================
    # Unit Test Examples
    # =========================================================================
    print("--- Running LLMJSONParser Tests ---\n")
    
    # 1. Perfect JSON
    perfect_json = '{"call_summary": "Great call.", "agent_score": 10}'
    
    # 2. Markdown Wrapper + Conversational Text
    markdown_json = '''
    Sure, here is the analysis you requested:
    ```json
    {
      "call_summary": "Issue resolved.",
      "agent_score": 9
    }
    ```
    Hope this helps! Let me know if you need anything else.
    '''
    
    # 3. Trailing Commas (Invalid in strict JSON)
    trailing_comma_json = '''
    {
      "call_summary": "Customer was happy",
      "agent_score": 8,
      "strengths": ["polite", "efficient",],
    }
    '''
    
    # 4. Malformed Arrays, Text Mixed, and Trailing Commas Combined
    mixed_json = '''Here it is: {"status": "resolved", "issues": [1, 2, 3,],}'''

    test_cases = [
        ("Perfect JSON", perfect_json),
        ("Markdown & Conversational Text", markdown_json),
        ("Trailing Commas Repair", trailing_comma_json),
        ("Mixed Complex Errors", mixed_json)
    ]

    for name, raw_text in test_cases:
        print(f"Testing: {name}")
        result = LLMJSONParser.parse(raw_text)
        if result:
            print(f"✅ SUCCESS: {result}\n")
        else:
            print("❌ FAILED\n")
