services:
  - type: web
    name: voxpulse
    env: docker
    dockerfilePath: Dockerfile
    plan: free


    envVars:
      - key: HF_TOKEN
        sync: false

      - key: PYTHONUNBUFFERED
        value: "true"

      - key: PORT
        value: "7860"